// Generated by ChatGPT 5.x Thinking based upon my specification for Kalman demo as follows:
//
// can you generate new code that has a point that rotates in a circle at a speed that is constant but has some noise;
// the speed should have a slider control for 0 to 100 where 0 is stopped and 100 is 10 rotations per second;
// the noise should have a slider to control amount of noise ranging from 0 degrees to 100 degrees;
// finally the point should be red and the tracing location should be a green box that can contain the point;
// add a simple button to turn on or off Kalman filtering with the OpenCV Kalman filter function
//
//   0 → 0.0 rotations/second
// 100 → 10.0 rotations/second
// each step = 0.1 rotations/second
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/video/tracking.hpp>

#include <chrono>
#include <cmath>
#include <cstdio>
#include <string>

using namespace cv;

static const char* kWindowName = "Kalman Circle Tracker";
static const int kCanvasSize = 800;
static const int kMarginTop = 110;
static const int kSpeedSliderMax = 100;
static const int kNoiseSliderMax = 100;

static int g_speedSlider = 0;   // 0..100 slider steps = 0.0..10.0 rotations per second
static int g_noiseSlider = 10;  // 0..100 degrees stddev
static bool g_useKalman = true;
static Rect g_buttonRect;

static inline double degToRad(double deg)
{
    return deg * CV_PI / 180.0;
}

static inline double wrapDrawAngle(double angle)
{
    const double twoPi = 2.0 * CV_PI;
    double wrapped = std::fmod(angle, twoPi);
    if (wrapped < 0.0)
        wrapped += twoPi;
    return wrapped;
}

static inline Point2f pointOnCircle(const Point2f& center, float radius, double angle)
{
    const double a = wrapDrawAngle(angle);
    return Point2f(
        center.x + radius * static_cast<float>(std::cos(a)),
        center.y - radius * static_cast<float>(std::sin(a)));
}

static inline double currentRotationsPerSecond()
{
    return static_cast<double>(g_speedSlider) * 0.1;
}

static inline double currentAngularVelocityRadPerSec()
{
    return currentRotationsPerSecond() * 2.0 * CV_PI;
}

static inline double currentNoiseStdRad()
{
    return degToRad(static_cast<double>(g_noiseSlider));
}

static void resetKalman(KalmanFilter& kf, double initialAngle, double initialOmega)
{
    kf.init(2, 1, 0, CV_32F);

    // state = [angle, angular_velocity]^T
    kf.transitionMatrix = (Mat_<float>(2, 2) << 1.f, 1.f, 0.f, 1.f);
    kf.measurementMatrix = (Mat_<float>(1, 2) << 1.f, 0.f);

    setIdentity(kf.processNoiseCov, Scalar::all(1e-4));
    kf.processNoiseCov.at<float>(0, 0) = 1e-4f;
    kf.processNoiseCov.at<float>(1, 1) = 5e-2f;

    setIdentity(kf.measurementNoiseCov, Scalar::all(1e-2));
    setIdentity(kf.errorCovPost, Scalar::all(1.f));

    kf.statePost = (Mat_<float>(2, 1) << static_cast<float>(initialAngle),
                     static_cast<float>(initialOmega));
    kf.statePre = kf.statePost.clone();
}

static void updateButtonRect(int imageWidth)
{
    const int buttonWidth = 170;
    const int buttonHeight = 36;
    g_buttonRect = Rect(imageWidth - buttonWidth - 20, 18, buttonWidth, buttonHeight);
}

static void onMouse(int event, int x, int y, int, void*)
{
    if (event == EVENT_LBUTTONDOWN && g_buttonRect.contains(Point(x, y)))
        g_useKalman = !g_useKalman;
}

static void drawButton(Mat& img)
{
    const Scalar fillColor = g_useKalman ? Scalar(60, 140, 60) : Scalar(80, 80, 80);
    rectangle(img, g_buttonRect, fillColor, FILLED, LINE_AA);
    rectangle(img, g_buttonRect, Scalar(220, 220, 220), 1, LINE_AA);

    const std::string label = g_useKalman ? "Kalman: ON" : "Kalman: OFF";
    putText(img, label,
            Point(g_buttonRect.x + 16, g_buttonRect.y + 24),
            FONT_HERSHEY_SIMPLEX, 0.65, Scalar(255, 255, 255), 2, LINE_AA);
}

int main()
{
    namedWindow(kWindowName, WINDOW_AUTOSIZE);
    createTrackbar("Speed (rot/s)", kWindowName, &g_speedSlider, kSpeedSliderMax);
    createTrackbar("Noise (deg)", kWindowName, &g_noiseSlider, kNoiseSliderMax);
    setMouseCallback(kWindowName, onMouse, nullptr);

    Mat img(kCanvasSize, kCanvasSize, CV_8UC3);
    const Point2f center(kCanvasSize * 0.5f, kCanvasSize * 0.58f);
    const float radius = 240.0f;
    const int boxHalfSize = 14;

    updateButtonRect(img.cols);

    // OpenCV Kalman Filter Class instance
    KalmanFilter kf;

    double trueAngle = 0.0;
    double measuredAngle = 0.0;
    double trackedAngle = 0.0;

    resetKalman(kf, trueAngle, currentAngularVelocityRadPerSec());

    RNG rng(getTickCount());
    auto lastTime = std::chrono::steady_clock::now();
    bool lastKalmanMode = g_useKalman;

    for (;;)
    {
        auto now = std::chrono::steady_clock::now();
        double dt = std::chrono::duration<double>(now - lastTime).count();
        lastTime = now;

        if (dt <= 0.0)
            dt = 1.0 / 60.0;
        if (dt > 0.1)
            dt = 0.1;

        const double omega = currentAngularVelocityRadPerSec();
        const double noiseStd = currentNoiseStdRad();

        if (lastKalmanMode != g_useKalman)
        {
            resetKalman(kf, trackedAngle, omega);
            lastKalmanMode = g_useKalman;
        }

        trueAngle += omega * dt;
        measuredAngle = trueAngle + rng.gaussian(noiseStd);

        // Update the filter dynamics for the current frame duration.
        kf.transitionMatrix.at<float>(0, 0) = 1.0f;
        kf.transitionMatrix.at<float>(0, 1) = static_cast<float>(dt);
        kf.transitionMatrix.at<float>(1, 0) = 0.0f;
        kf.transitionMatrix.at<float>(1, 1) = 1.0f;

        // Measurement noise is controlled by the noise slider.
        kf.measurementNoiseCov.at<float>(0, 0) =
            static_cast<float>(std::max(noiseStd * noiseStd, 1e-9));

        // Keep the model's velocity close to the slider-controlled speed.
        kf.statePost.at<float>(1) = static_cast<float>(omega);
        kf.statePre.at<float>(1) = static_cast<float>(omega);

        Mat prediction = kf.predict();
        prediction.at<float>(1) = static_cast<float>(omega);

        Mat measurement(1, 1, CV_32F);
        measurement.at<float>(0) = static_cast<float>(measuredAngle);

        Mat estimate;
        if (g_useKalman)
        {
            estimate = kf.correct(measurement);
            estimate.at<float>(1) = static_cast<float>(omega);
            kf.statePost.at<float>(1) = static_cast<float>(omega);
            trackedAngle = static_cast<double>(estimate.at<float>(0));
        }
        else
        {
            trackedAngle = measuredAngle;
            resetKalman(kf, trackedAngle, omega);
        }

        const Point2f truePt = pointOnCircle(center, radius, trueAngle);
        const Point2f trackedPt = pointOnCircle(center, radius, trackedAngle);

        img.setTo(Scalar(20, 20, 20));

        circle(img, center, static_cast<int>(radius), Scalar(80, 80, 80), 1, LINE_AA);
        line(img, Point(static_cast<int>(center.x - radius - 20), static_cast<int>(center.y)),
             Point(static_cast<int>(center.x + radius + 20), static_cast<int>(center.y)),
             Scalar(45, 45, 45), 1, LINE_AA);
        line(img, Point(static_cast<int>(center.x), static_cast<int>(center.y - radius - 20)),
             Point(static_cast<int>(center.x), static_cast<int>(center.y + radius + 20)),
             Scalar(45, 45, 45), 1, LINE_AA);

        Rect trackBox(static_cast<int>(trackedPt.x) - boxHalfSize,
                      static_cast<int>(trackedPt.y) - boxHalfSize,
                      boxHalfSize * 2,
                      boxHalfSize * 2);
        rectangle(img, trackBox, Scalar(0, 255, 0), 2, LINE_AA);
        circle(img, truePt, 6, Scalar(0, 0, 255), FILLED, LINE_AA);

        putText(img, "Red point: true location", Point(20, 30), FONT_HERSHEY_SIMPLEX,
                0.65, Scalar(220, 220, 220), 2, LINE_AA);
        putText(img, "Green box: tracked location", Point(20, 58), FONT_HERSHEY_SIMPLEX,
                0.65, Scalar(220, 220, 220), 2, LINE_AA);

        char speedText[128];
        std::snprintf(speedText, sizeof(speedText), "Speed: %.1f rot/s", currentRotationsPerSecond());
        putText(img, speedText, Point(20, 88), FONT_HERSHEY_SIMPLEX,
                0.65, Scalar(255, 255, 255), 2, LINE_AA);

        char noiseText[128];
        std::snprintf(noiseText, sizeof(noiseText), "Noise: %d deg", g_noiseSlider);
        putText(img, noiseText, Point(20, 116), FONT_HERSHEY_SIMPLEX,
                0.65, Scalar(255, 255, 255), 2, LINE_AA);

        drawButton(img);

        putText(img, "Press R to reset, ESC or Q to quit", Point(20, img.rows - 20),
                FONT_HERSHEY_SIMPLEX, 0.6, Scalar(200, 200, 200), 1, LINE_AA);

        imshow(kWindowName, img);
        const int key = waitKey(1);
        if (key == 27 || key == 'q' || key == 'Q')
            break;
        if (key == 'r' || key == 'R')
        {
            trueAngle = 0.0;
            measuredAngle = 0.0;
            trackedAngle = 0.0;
            resetKalman(kf, trueAngle, currentAngularVelocityRadPerSec());
        }
    }

    return 0;
}

